FROM scratch

COPY model-files/Qwen3VL-4B-Instruct-Q4_K_M.gguf /Qwen3VL-4B-Instruct-Q4_K_M.gguf
COPY model-files/mmproj-Qwen3VL-4B-Instruct-F16.gguf /mmproj-Qwen3VL-4B-Instruct-F16.gguf

LABEL model="Qwen3VL-4B-Instruct-Q4_K_M" \
      format="gguf"
