package catalog

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	derrors "github.com/xynova/library-intake/internal/errors"
)

const (
	additionsDirName = "additions"
	weekStatusOpen   = "open"
	weekStatusClosed = "closed"
)

// RebuildAdditions regenerates weekly files and additions/INDEX.md from entry
// added dates. Status is date-driven: the current ISO week is open; earlier
// weeks are closed. There is no manual close step.
func RebuildAdditions(libraryRoot string, now time.Time) error {
	op := "catalog.RebuildAdditions"
	entries, err := ScanEntries(libraryRoot)
	if err != nil {
		return err
	}
	byWeek := map[string][]Entry{}
	for _, e := range entries {
		wid, err := e.ISOWeekID()
		if err != nil {
			return err
		}
		byWeek[wid] = append(byWeek[wid], e)
	}
	current := CurrentISOWeekID(now)
	dir := filepath.Join(libraryRoot, additionsDirName)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return derrors.Wrap(err, derrors.CodeFailed, op, "mkdir additions").With("path", dir)
	}
	weeks := make([]string, 0, len(byWeek))
	for w := range byWeek {
		weeks = append(weeks, w)
	}
	sort.Sort(sort.Reverse(sort.StringSlice(weeks)))
	openWeek := ""
	for i, wid := range weeks {
		status := weekStatusClosed
		closed := lastDayOfISOWeek(wid).Format("2006-01-02")
		if wid == current {
			status = weekStatusOpen
			closed = ""
			openWeek = wid
		}
		list := byWeek[wid]
		sortWeekEntries(list)
		// Newest week first in Hugo/Hextra sidebar (lower weight sorts higher).
		weight := i + 1
		if err := writeWeekFile(libraryRoot, wid, status, closed, weight, list); err != nil {
			return err
		}
	}
	return writeAdditionsIndex(libraryRoot, weeks, byWeek, openWeek)
}

func sortWeekEntries(list []Entry) {
	sort.Slice(list, func(i, j int) bool {
		if list[i].Category != list[j].Category {
			return list[i].Category < list[j].Category
		}
		if list[i].Added != list[j].Added {
			return list[i].Added > list[j].Added
		}
		return list[i].Name < list[j].Name
	})
}

func weekPath(libraryRoot, weekID string) string {
	return filepath.Join(libraryRoot, additionsDirName, weekID+".md")
}

func writeWeekFile(libraryRoot, weekID, status, closed string, weight int, entries []Entry) error {
	op := "catalog.writeWeekFile"
	rangeLabel := FormatWeekRange(weekID)
	start := firstDayOfISOWeek(weekID)
	end := lastDayOfISOWeek(weekID)
	var b strings.Builder
	b.WriteString("---\n")
	fmt.Fprintf(&b, "title: %q\n", rangeLabel)
	fmt.Fprintf(&b, "week: %s\n", weekID)
	fmt.Fprintf(&b, "week_start: %s\n", start.Format("2006-01-02"))
	fmt.Fprintf(&b, "week_end: %s\n", end.Format("2006-01-02"))
	fmt.Fprintf(&b, "status: %s\n", status)
	if closed != "" {
		fmt.Fprintf(&b, "closed: %s\n", closed)
	}
	fmt.Fprintf(&b, "weight: %d\n", weight)
	b.WriteString("type: docs\n")
	b.WriteString("---\n\n")
	fmt.Fprintf(&b, "# %s\n\n", rangeLabel)
	fmt.Fprintf(&b, "ISO week **%s** (%s – %s).\n\n",
		weekID, start.Format("Mon 2 Jan"), end.Format("Mon 2 Jan 2006"))
	if status == weekStatusOpen {
		b.WriteString("Current week of library additions (from each entry's `added` date).\n\n")
	} else {
		b.WriteString("Earlier week of library additions.\n\n")
	}

	byCat := map[string][]Entry{}
	cats := make([]string, 0)
	for _, e := range entries {
		if _, ok := byCat[e.Category]; !ok {
			cats = append(cats, e.Category)
		}
		byCat[e.Category] = append(byCat[e.Category], e)
	}
	sort.Strings(cats)
	for _, cat := range cats {
		fmt.Fprintf(&b, "## %s\n\n", cat)
		b.WriteString("| name | title | summary | tags | run | license |\n")
		b.WriteString("|------|-------|---------|------|-----|---------|\n")
		for _, e := range byCat[cat] {
			fmt.Fprintf(&b, "| [%s](../%s) | %s | %s | %s | %s | %s |\n",
				e.Name, e.Path, e.Title, TableCell(e.Summary), strings.Join(e.Tags, ", "), e.Run, e.License)
		}
		b.WriteString("\n")
	}
	if len(entries) == 0 {
		b.WriteString("_No entries this week._\n")
	}
	path := weekPath(libraryRoot, weekID)
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return derrors.Wrap(err, derrors.CodeFailed, op, "write week file").
			With("path", path).
			With("week", weekID)
	}
	return nil
}

func writeAdditionsIndex(libraryRoot string, weeks []string, byWeek map[string][]Entry, openWeek string) error {
	op := "catalog.writeAdditionsIndex"
	var b strings.Builder
	b.WriteString("# Additions index\n\n")
	b.WriteString("Weekly library additions from entry `added` dates. Regenerated by `library-intake index refresh`.\n\n")
	b.WriteString("| week | dates | status | count | path |\n")
	b.WriteString("|------|-------|--------|-------|------|\n")
	for _, wid := range weeks {
		status := weekStatusClosed
		if wid == openWeek {
			status = weekStatusOpen
		}
		fmt.Fprintf(&b, "| %s | %s | %s | %d | %s.md |\n", wid, FormatWeekRange(wid), status, len(byWeek[wid]), wid)
	}
	path := filepath.Join(libraryRoot, additionsDirName, "INDEX.md")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return derrors.Wrap(err, derrors.CodeFailed, op, "mkdir additions").With("path", filepath.Dir(path))
	}
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return derrors.Wrap(err, derrors.CodeFailed, op, "write additions INDEX.md").With("path", path)
	}
	return nil
}

// firstDayOfISOWeek returns the Monday of the given YYYY-Www week.
func firstDayOfISOWeek(weekID string) time.Time {
	end := lastDayOfISOWeek(weekID)
	if end.IsZero() {
		return time.Time{}
	}
	return end.AddDate(0, 0, -6)
}

// FormatWeekRange returns a human date span like "Sep 14–20, 2026".
func FormatWeekRange(weekID string) string {
	start := firstDayOfISOWeek(weekID)
	end := lastDayOfISOWeek(weekID)
	if start.IsZero() || end.IsZero() {
		return weekID
	}
	if start.Year() == end.Year() && start.Month() == end.Month() {
		return fmt.Sprintf("%s %d–%d, %d", start.Format("Jan"), start.Day(), end.Day(), start.Year())
	}
	if start.Year() == end.Year() {
		return fmt.Sprintf("%s %d – %s %d, %d",
			start.Format("Jan"), start.Day(), end.Format("Jan"), end.Day(), start.Year())
	}
	return fmt.Sprintf("%s %d, %d – %s %d, %d",
		start.Format("Jan"), start.Day(), start.Year(),
		end.Format("Jan"), end.Day(), end.Year())
}

// lastDayOfISOWeek returns the Sunday of the given YYYY-Www week.
func lastDayOfISOWeek(weekID string) time.Time {
	var year, week int
	if _, err := fmt.Sscanf(weekID, "%d-W%d", &year, &week); err != nil {
		return time.Time{}
	}
	jan4 := time.Date(year, time.January, 4, 0, 0, 0, 0, time.Local)
	wd := int(jan4.Weekday())
	if wd == 0 {
		wd = 7
	}
	mondayWeek1 := jan4.AddDate(0, 0, -(wd - 1))
	monday := mondayWeek1.AddDate(0, 0, (week-1)*7)
	return monday.AddDate(0, 0, 6)
}
