package catalog

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	derrors "github.com/xynova/library-intake/internal/errors"
)

// RefreshIndexes regenerates library/INDEX.md and library/<category>/INDEX.md.
func RefreshIndexes(libraryRoot string) error {
	if _, err := BackfillSummaries(libraryRoot); err != nil {
		return err
	}
	entries, err := ScanEntries(libraryRoot)
	if err != nil {
		return err
	}
	if err := writeGlobalIndex(libraryRoot, entries); err != nil {
		return err
	}
	cats, err := ListCategoryDirs(libraryRoot)
	if err != nil {
		return err
	}
	byCat := map[string][]Entry{}
	for _, e := range entries {
		byCat[e.Category] = append(byCat[e.Category], e)
	}
	for _, cat := range cats {
		if err := writeCategoryIndex(libraryRoot, cat, byCat[cat]); err != nil {
			return err
		}
	}
	return nil
}

func writeGlobalIndex(libraryRoot string, entries []Entry) error {
	op := "catalog.writeGlobalIndex"
	var b strings.Builder
	b.WriteString("# Library index\n\n")
	b.WriteString("Regenerated by `library-intake index refresh` after writes.\n\n")
	b.WriteString("| name | title | category | summary | tags | run | license |\n")
	b.WriteString("|------|-------|----------|---------|------|-----|---------|\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s | %s | %s |\n",
			e.Name, e.Title, e.Category, TableCell(e.Summary), strings.Join(e.Tags, ", "), e.Run, e.License)
	}
	path := filepath.Join(libraryRoot, "INDEX.md")
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return derrors.Wrap(err, derrors.CodeFailed, op, "write INDEX.md").With("path", path)
	}
	return nil
}

func writeCategoryIndex(libraryRoot, category string, entries []Entry) error {
	op := "catalog.writeCategoryIndex"
	var b strings.Builder
	fmt.Fprintf(&b, "# %s index\n\n", category)
	b.WriteString("Regenerated by `library-intake index refresh` after writes.\n\n")
	b.WriteString("| name | title | summary | tags | run | license |\n")
	b.WriteString("|------|-------|---------|------|-----|---------|\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s | %s |\n",
			e.Name, e.Title, TableCell(e.Summary), strings.Join(e.Tags, ", "), e.Run, e.License)
	}
	path := filepath.Join(libraryRoot, category, "INDEX.md")
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return derrors.Wrap(err, derrors.CodeFailed, op, "write category INDEX.md").
			With("path", path).
			With("category", category)
	}
	return nil
}
