FROM scratch

COPY model-files/gemma-4-12B-it-QAT-Q4_0.gguf /gemma-4-12B-it-QAT-Q4_0.gguf
COPY model-files/mmproj-gemma-4-12B-it-QAT-BF16.gguf /mmproj-gemma-4-12B-it-QAT-BF16.gguf

LABEL model="gemma-4-12B-it-QAT-Q4_0" \
      format="gguf"
